const people = [
  {
    name: 'Marty Kaan',
    price: 20,
    position: 'Partner',
    company: 'Kaan & Associates',
    avatar: 'http://www.media4.hw-static.com/wp-content/uploads/don-cheadle-house-of-lies_47958751-368x314-368x314.jpeg',
    industry: 'Management Consulting',
    starRating: '4',
    yearsOfExperience: 15,
    canHelpWith: ['General Advice', 'Informational Interviews', 'Interview Prep']
  },
  {
    name: 'Srilaxman Kishor Ramanthan',
    price: 50,
    position: 'Partner',
    company: 'BCG',
    avatar: 'http://www.google.com/imgres?imgurl=https://directory.engr.wisc.edu/private/includes/profilePictures/r/ramanathan_parameswaran.jpg&imgrefurl=http://www.engr.wisc.edu/ece/faculty/ramanathan_parameswaran.html&h=232&w=165&tbnid=7xf_mYbjj3wYEM:&docid=edvGvLmgtvmxPM&ei=dwtRVpvlEsz0-AHlsIGYAg&tbm=isch&ved=0ahUKEwjb_NSp4qLJAhVMOj4KHWVYACMQMwgoKAswCw',
    industry: 'Management Consulting',
    yearsOfExperience: 5,
  },
  {
    name: 'Daniel Stumner',
    price: 35,
    position: 'Managing Principal',
    company: 'Booz',
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/c_southam/128.jpg',
    industry: 'Management Consulting',
    yearsOfExperience: 5,
  },
  {
    name: 'Kelly Glick',
    price: 30,
    position: 'Principal Consultant',
    company: 'Capco',
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/kfriedson/128.jpg',
    industry: 'Management Consulting',
    yearsOfExperience: 5,
  },
  {
    name: 'Lorenzo Pascal',
    price: 25,
    position: 'Senior Consultant',
    company: 'PwC',
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/vocino/128.jpg',
    industry: 'Strategy Consulting, Financial Advisory',
    yearsOfExperience: 5,
  },
  {
    name: 'Joel Sloky',
    price: 40,
    position: 'Senior Consultant',
    company: 'Accenture',
    avatar: 'https://s3.amazonaws.com/uifaces/faces/twitter/dakshbhagya/128.jpg',
    industry: 'Strategy Consulting',
    yearsOfExperience: 5,
  },
  {
    name: 'Monica Talbot',
    price: 50,
    position: 'Partner',
    company: 'Kinsley Johnson',
    avatar: 'http://vignette2.wikia.nocookie.net/houseoflies/images/7/75/Monica.jpg/revision/latest?cb=20130115121100',
    industry: 'Managment Consulting',
    yearsOfExperience: 5,
  },
  {
    name: 'Jeannie Van Der Hooven',
    price: 50,
    position: 'Engagement Manager',
    company: 'Galweather & Stearn',
    avatar: 'http://assets.wornon.tv/uploads/2014/01/jeannies-printed-blouse-studded-jacket.jpg',
    industry: 'Management Consulting',
    yearsOfExperience: 5,
  },
  {
    name: 'Clyde Oberholt',
    price: 50,
    position: 'Senior Consultant',
    company: 'Kinsley-Johnson',
    avatar: 'http://ia.media-imdb.com/images/M/MV5BMTQwNDgyNTgxNl5BMl5BanBnXkFtZTgwNjM0MzY0MTE@._V1_SX1333_CR0,0,1333,1774_AL_.jpg',
    industry: 'Management Consulting',
    yearsOfExperience: 5,
  },
  {
    name: 'Doug Guggenheim',
    price: 50,
    position: 'Senior Consultant',
    company: 'Kaan & Associates',
    avatar: 'http://vignette4.wikia.nocookie.net/houseoflies/images/9/9b/Dougg.jpg/revision/latest?cb=20130116032041',
    industry: 'Management Consulting',
    yearsOfExperience: 5,
  },
]

module.exports = people;
